### ISSUE TITLE
Trying to use i18n with stencilJs 

### ISSUE THREAD

**Issue by raygonsalvez** [spurreiter/i18next-wc#1]
Hello,

We are creating web components using stencilJS and want to implement i18n language support. Tried using the examples specified here and none of our keys are rendering.

```
i18next.init({
    lng: 'en-US',
    fallbackLng: 'en',
    resources: {
        en: {
            default: {
                identifier: 'to',
            },
        },
        'en-US': {
            default: {
                identifier: 'to',
            },
        },
        'es-US': {
            default: {
                identifier: 'a',
            },
        },
        fr: {
            default: {
                identifier: 'vers',
            },
        },
    },
    defaultNS: 'default',
    fallbackNS: 'global',
})
```

`<intl-message key='identifier'></intl-message>`

Can you please let us know what we are missing?

**Comment by spurreiter** [comment]
Hi @raygonsalvez, This is difficult to say what may be wrong with your code. 
I am not in-depth familiar with stencilJS. Maybe you can share a sample project in order to see what is happening. What is important to consider is, before loading the js for intl-message, window.i18next must be available in order to render the message. 
```js
// non funct code
import i18next from 'i18next'
window.i18next = i18next // <<< Maybe you'll missing this line?

i18next.init()

class Component {
  render () {
    return <intl-message ...>
  }
}
```
If you don't want to pollute the global context please check https://github.com/spurreiter/i18next-wc/blob/ca0f381e1e169f053942d9ef9dd578e32c432bd9/test/jsx/test.tsx#L55

**Comment by spurreiter** [comment]
Please reopen if problem still persists.
